/**
 * Shared PDF generation for army list export.
 *
 * Used by both ArmyListDetailPage and ArmyListDetailSheet to avoid
 * duplicating the ~80-line jsPDF + autoTable rendering logic.
 */

import type { ExportData } from "@/lib/exportArmyList";
import { dateStamp } from "@/lib/exportArmyList";

/**
 * Generate an army list PDF and return the raw ArrayBuffer.
 * Lazy-loads jsPDF and jspdf-autotable on first call.
 */
export async function generateArmyListPdf(
  data: ExportData,
  listName: string,
  detachmentName: string | null,
  pointsLimit: number | null,
): Promise<ArrayBuffer> {
  const { jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable = autoTableModule.default;

  const doc = new jsPDF({ orientation: "p", unit: "mm", format: "a4" });
  const grandTotal = data.totalPoints + data.enhancementTotal;

  // Header -- army name
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(listName, 20, 25);

  // Metadata line
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 51, 51);
  doc.text(
    `Faction: ${data.factionName ?? "None"}  |  Detachment: ${detachmentName ?? "None"}  |  ${dateStamp()}`,
    20,
    33,
  );
  doc.setTextColor(0, 0, 0);

  // Units table
  const unitRows = data.sortedUnits.map((u) => {
    let name = u.displayName;
    if (u.isGhost) name += " (Planned)";
    if (u.isWarlord) name += " (Warlord)";
    const notes = u.leaderLabel ?? u.enhancementName ?? "";
    return [name, `${u.points}pts`, notes];
  });

  autoTable(doc, {
    startY: 40,
    head: [["Unit", "Points", "Notes"]],
    body: unitRows,
    styles: { fontSize: 9 },
    headStyles: { fillColor: [60, 60, 60] },
    margin: { left: 20, right: 20 },
  });

  // Enhancements section
  if (data.enhancements.length > 0) {
    const lastY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? 100;
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text("Enhancements", 20, lastY + 10);

    autoTable(doc, {
      startY: lastY + 14,
      head: [["Enhancement", "Points"]],
      body: data.enhancements.map((e) => [e.enhancement_name, `${e.enhancement_points}pts`]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [60, 60, 60] },
      margin: { left: 20, right: 20 },
    });
  }

  // Totals line
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? 120;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(
    `Total: ${grandTotal}pts${pointsLimit ? ` / ${pointsLimit}pts` : ""}`,
    20,
    finalY + 10,
  );

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(153, 153, 153);
  doc.text("Generated by HobbyForge", pageWidth - 20, pageHeight - 10, { align: "right" });

  return doc.output("arraybuffer");
}
